<?php

use Illuminate\Database\Seeder;

class TinTucSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tin_tuc_translations')->insert([
        [
        	'tin_tuc_id' => '1',
        	'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
        	'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
        	'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
        	'locale' => 'vi',
        ],
         [
            'tin_tuc_id' => '1',
            'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
            'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
            'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
            'locale' => 'en',
        ],
         [
            'tin_tuc_id' => '2',
            'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
            'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
            'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
            'locale' => 'vi',
        ],
         [
            'tin_tuc_id' => '2',
            'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
            'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
            'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
            'locale' => 'en',
        ],
         [
            'tin_tuc_id' => '3',
            'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
            'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
            'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
            'locale' => 'vi',
        ],
         [
            'tin_tuc_id' => '3',
            'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
            'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
            'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
            'locale' => 'en',
        ],
         [
            'tin_tuc_id' => '4',
            'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
            'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
            'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
            'locale' => 'vi',
        ],
         [
            'tin_tuc_id' => '4',
            'Ten' => 'Hội thảo giới thiệu và kết nối các giải pháp công nghệ xanh cho doanh nghiệp vừa và nhỏ',
            'NoiDung' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>

            <p>Với c&aacute;c doanh nghiệp vừa v&agrave; nhỏ (DNVVN), c&ocirc;ng nghệ xử l&yacute; nước thải thường rất &iacute;t được coi trọng. Với những DNVVN trong c&aacute;c khu c&ocirc;ng nghiệp, thường c&ocirc;ng nghệ xử l&yacute; nước thải phần n&agrave;o bị lạc hậu, hiệu quả kh&ocirc;ng cao. C&ograve;n c&aacute;c DNVVN nằm trong khu d&acirc;n cư, hệ thống xử l&yacute; nước thải rất dễ bị lơ l&agrave; do kinh ph&iacute; x&acirc;y dựng kh&ocirc;ng hề nhỏ.</p>

            <p>Hiểu được t&igrave;nh h&igrave;nh tr&ecirc;n, Trung t&acirc;m Ươm tạo C&ocirc;ng nghệ v&agrave; Doanh nghiệp Khoa học C&ocirc;ng nghệ tổ chức hội thảo&nbsp;<strong>&ldquo;Giới thiệu v&agrave; kết nối c&aacute;c giải ph&aacute;p c&ocirc;ng nghệ xanh cho doanh nghiệp vừa v&agrave; nhỏ&rdquo;</strong>.&nbsp;<strong>Hội thảo được tổ chức từ 8h30 &ndash; 12h00 ng&agrave;y 3/3/2017 tại ph&ograve;ng VIP D, tầng 2 nh&agrave; D, Nh&agrave; kh&aacute;ch La Th&agrave;nh, 226 Vạn Ph&uacute;c, Ba Đ&igrave;nh, H&agrave; Nội.</strong></p>

            <p>Tại hội thảo, c&aacute;c diễn giả sẽ giới thiệu một số giải ph&aacute;p xử l&yacute; nước thải c&oacute; sử dụng c&aacute;c c&ocirc;ng nghệ kh&aacute;c nhau ph&ugrave; hợp với những đối tượng doanh nghiệp ở c&aacute;c lĩnh vực kh&aacute;c nhau. Ngo&agrave;i ra, hội thảo cũng giới thiệu một số c&ocirc;ng nghệ xanh ứng dụng trong n&ocirc;ng nghiệp của &Aacute;o.</p>

            <p>Hội thảo cũng d&agrave;nh rất nhiều thời gian để c&aacute;c diễn giả v&agrave; kh&aacute;ch mời giao lưu, chia sẻ, hỏi đ&aacute;p cũng như tư vấn về c&ocirc;ng nghệ xanh. Ch&uacute;ng t&ocirc;i hy vọng rằng, đến với hội thảo n&agrave;y, c&aacute;c kh&aacute;ch mời, đặc biệt l&agrave; c&aacute;c doanh nghiệp vừa v&agrave; nhỏ t&igrave;m được c&ocirc;ng nghệ ph&ugrave; hợp để ứng dụng cho doanh nghiệp của m&igrave;nh cũng như c&oacute; cơ hội gặp gỡ c&aacute;c chuy&ecirc;n gia v&agrave; c&aacute;c doanh nghiệp kh&aacute;c để hợp t&aacute;c c&ugrave;ng ph&aacute;t triển.</p>',
            'TomTat' => '<p>Tại c&aacute;c quốc gia ph&aacute;t triển tr&ecirc;n thế giới, trong v&agrave;i thập ni&ecirc;n gần đ&acirc;y, &ldquo;c&ocirc;ng nghệ xanh&rdquo; đ&atilde; nhận được nhiều sự quan t&acirc;m của ch&iacute;nh phủ cũng như khu vực tư nh&acirc;n v&agrave; giới khoa học. Nhiều chuy&ecirc;n gia nhận định c&ocirc;ng nghệ xanh l&agrave; một trong những giải ph&aacute;p h&agrave;ng đầu trong c&ocirc;ng cuộc chống biến đổi kh&iacute; hậu, đồng thời cũng l&agrave; một lĩnh vực tr&agrave;n đầy triển vọng ph&aacute;t triển trong tương lai. Bởi vậy, c&aacute;c quốc gia theo đuổi c&ocirc;ng nghệ xanh nghĩa l&agrave; kh&ocirc;ng chỉ hướng tới mục ti&ecirc;u m&ocirc;i trường m&agrave; c&ograve;n nhắm tới một lĩnh vực c&oacute; khả năng tạo sinh kh&iacute; mới cho nền kinh tế.</p>',
            'locale' => 'en',
        ]
        ]);
    }
}
